### PR TITLE
accomodate Zig changes to std.builtin.Type

### PR DESCRIPTION
**Pull request by StringNick**

### CODE REVIEW

**Comment by sam701** [comment]
@StringNick Thanks for your contribution! The build in `examples/standalone` dir failed (see the PR checks). Could you have a look?

**Comment by StringNick** [comment]
@sam701 i am not sure that i can fix standalone test, because its pointing on some version of zig cli, i can put my fork, but i dont think that's okay

**Comment by StringNick** [comment]
Something like that:
https://github.com/sam701/zig-cli/blob/74fc6535e5e5c36e582bad3c41a7eba2f7ac0f31/examples/standalone/build.zig.zon#L7-L8

**Comment by sam701** [comment]
Ah, got it. It is indeed inconvenient for contribution. The build failed because of the invalid URI. Don't you mind to revert you last commit? I will then merge your PR and later remove the standalone build from the PR checks.

**Pull request merged**
